#Custom Gitleaks Config

[allowlist]
description = "Allowlisted paths and secrets"
paths = [".github/workflows/ci-cd.yml"]

[[rules]]
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "AWS Secret Key"
regex = '''(?i)aws_secret_access_key\s*=\s*["']?[A-Za-z0-9/+=]{40}["']?'''
tags = ["key", "AWS"]

[[rules]]
description = "Generic Secret Key"
regex = '''(?i)secret_key\s*=\s*["'].*["']'''
tags = ["key", "generic"]

